### ISSUE TITLE
Put on Maven Central for use in other plugins

### ISSUE THREAD

**Issue by DarthHater** [focusenergy/JavaRDS#1]
Hi!

It's rad you created this! I'd love to play with it in the nexus-repository-r project, think you can deploy it to Maven Central so we can consume it easier?

Cheers!
Jeffry / @bhamail

**Comment by kenahoo** [comment]
I'd love to, and intend to - but the process is new to me so it's probably going to take me a while...

**Comment by kenahoo** [comment]
Hi @DarthHater - I was finally able to navigate this process, version 0.1 is now on Maven Central:

https://search.maven.org/search?q=a:JavaRDS

Let me know if anything looks wacky, or too hard to figure out.

**Comment by DarthHater** [comment]
RAD!!!! @tyanko1 might want to chat with you about your process of putting it up there @kenahoo , FYI

**Comment by tyanko1** [comment]
Hey @kenahoo ! Glad to hear you made it through the publishing process. If you're interested at all in sharing your experience, we're currently conducting interviews with users as we work to refine our onboarding procedures. Feel free to sign up at the following link if you would like to participate: https://www.surveymonkey.com/r/HHZXMSW
