### ISSUE TITLE
Fix style/naming issues

### ISSUE THREAD

**Issue by kenahoo** [focusenergy/JavaRDS#2]
There are several style/naming issues in the v0.1 release that I would like to fix.  It necessitates breaking some backwards compatibility, e.g. changing `write_rds()` to `writeRDS()`, etc.

@darthhater, @bhamail - let me know if this would be a pain, I could do a deprecation period if necessary.

**Comment by kenahoo** [comment]
I uploaded a `0.2-SNAPSHOT` with (some of?) these changes.

**Comment by DarthHater** [comment]
None of this is deal breakers for us (we've yet to use it). Suggestion would be to create new method signatures with your preferred name, and just call the old ones, and mark those as `@Deprecated`
